### ISSUE TITLE
Example: How to solve nonlinear equations?

### ISSUE THREAD

**Issue by BrushXue** [BrushXue/ME423-HelpDesk#1]
How to solve non-linear equations in assignment 1?
I don't know how to deal with the <img src="https://render.githubusercontent.com/render/math?math=\theta^4"> term.

**Comment by BrushXue** [comment]
In MATLAB use [fsolve](https://www.mathworks.com/help/optim/ug/fsolve.html)
```MATLAB
x = fsolve(func,x0)
```
In Python use [fsolve](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fsolve.html)
```Python
from scipy.optimize import fsolve
root = fsolve(func, x0)
```

**Comment by hanzla848** [comment]
Using fsolve or any iterative method (like Newton Raphson) we can solve for each  T1, Tin, Ts & q for each given Ti.
But we need an initial guess for fsolve or any iterative method. Can we use values of T1, Tin, Ts, and q from previous Ti as a guess for the next Ti (Ti varying from 1-40)?

**Comment by BrushXue** [comment]
@hanzla848
A good first initial guess would be
<img src="https://render.githubusercontent.com/render/math?math=\large\bar{q}=0,\ T_1=T_i,\ T_{in}=1,\ T_S=1">
which works for a simple case like this.
If the equation is too stiff, you'll have to change the initial value progressively. e.g. use the result from Ti=20 as the initial value of Ti=21.
