### ISSUE TITLE
Question about problem b

### ISSUE THREAD

**Issue by JackyPoka** [BrushXue/ME423-HelpDesk#10]
Hi Guanyang:

Just for the confirmation. For problem b, we are asked to find the solution using normal mode analysis and finite difference. Is this mean, we need to combine this two method to solve the problem and draw contours of θ(X,Y), or we should separate them to solve it?

Thank you.

**Comment by BrushXue** [comment]
It means you need to derive the analytical solution and plot it.
Then use finite difference to calculate the numerical solution and plot it.
Two solutions should match.

**Comment by JackyPoka** [comment]
Thank you, Guanyang!

**Comment by JackyPoka** [comment]
Sorry, another question about problem b. The problem asked us to draw contours of θ(X,Y), should we apply a/c=1 while we calculate ? It seems could find the solution without applying this condition. Or maybe, I might think it in a wrong way. Thank you.

**Comment by BrushXue** [comment]
the z-axis is ignored as two boundaries are adiabatic. The x-y 2D problem has nothing to do with **c**.

**Comment by JackyPoka** [comment]
Got it! Thank you. Since a/c has appeared in problem b, I was confused by it.
