### ISSUE TITLE
Solving for eigenvalues

### ISSUE THREAD

**Issue by kpw320** [BrushXue/ME423-HelpDesk#11]
When we are finding the eigenvalues and its a nonlinear equation, we get a bunch of solutions from whatever solver we use. Some of the solutions are negative. But we are summing from n=1 to some number of eigenvalues and functions to construct a normal mode solution. Do we only pick the positive roots and assign those in order from 1 to whatever number of eigenvalues we end up using? Or is there some way we need to include the negative eigenvalues.

**Comment by BrushXue** [comment]
To make it easier to understand you only need positive eigenvalues.
Well, mathematically if you choose negative eigenvalues the result won't change. You can see that from the equation.
