### ISSUE TITLE
Defining 's' In Laplace Transform 

### ISSUE THREAD

**Issue by JackyPoka** [BrushXue/ME423-HelpDesk#13]
Hi Guanyang:

I have a question about dealing with 's' in Laplace transform. I'm using Laplace transform as my analytical solution. However, I still have 's' exist in my equation after doing inverse Laplace transform. Could I know how to define 's' in MATLAB? or is there any specific way to draw the curve without defining it? Thank you.

**Comment by BrushXue** [comment]
There shouldn't be any `s` after the inverse transform. If you see any of them, please simplify you equation.

**Comment by BrushXue** [comment]
<img width="729" alt="Screen Shot 2021-03-23 at 7 38 52 PM" src="https://user-images.githubusercontent.com/12702149/112233221-67933c80-8c10-11eb-915d-3d14d3e25814.png">
<img width="730" alt="Screen Shot 2021-03-23 at 7 39 11 PM" src="https://user-images.githubusercontent.com/12702149/112233228-695d0000-8c10-11eb-92fb-c660e4afd5f0.png">
<img width="730" alt="Screen Shot 2021-03-23 at 7 39 20 PM" src="https://user-images.githubusercontent.com/12702149/112233295-901b3680-8c10-11eb-9f81-e541ff1cb194.png">
<img width="730" alt="Screen Shot 2021-03-23 at 7 39 30 PM" src="https://user-images.githubusercontent.com/12702149/112233354-b04af580-8c10-11eb-928c-dc79300e4f67.png">
<img width="730" alt="Screen Shot 2021-03-23 at 7 39 37 PM" src="https://user-images.githubusercontent.com/12702149/112233409-ca84d380-8c10-11eb-8e80-9c34948d4619.png">
<img width="729" alt="Screen Shot 2021-03-23 at 7 39 49 PM" src="https://user-images.githubusercontent.com/12702149/112233475-e38d8480-8c10-11eb-8bd8-c1a1bb59277f.png">

**Comment by BrushXue** [comment]
I'll leave this issue open, in case anyone needs to read it.
