### ISSUE TITLE
Analytical solution giving odd answer

### ISSUE THREAD

**Issue by kpw320** [BrushXue/ME423-HelpDesk#16]
My analytical solution produces a very wrong answer in short time. I understand that maybe this solution won't be very accurate in the short time, but it's just way too off. I've looked over my math repeatedly and can't find any mistakes. The analytical solution seems accurate in long time. Is there a chance I've got a correct expression and the issue has to do with terms and convergence, or is it likely I've made a mistake somewhere.

**Comment by BrushXue** [comment]
The analytical solution should be accurate at any time.
The convergence can be an issue so try to increase `n`

**Comment by BrushXue** [comment]
n=100 should be enough. So it seems like your mathematics expression is wrong.
Based on your description that long time solution is accurate, there might be something wrong with your exponential term.
