### ISSUE TITLE
Question regarding Assignment 5

### ISSUE THREAD

**Issue by kershj** [BrushXue/ME423-HelpDesk#17]
I have a question regarding Assignment 5. If I am remembering correctly, Prof. Oztekin said that the dT/dx term could be solved using implicit differentiation, which we have used in the past, and the d^2T/dY^2 term requires simple integration. I am trying to get a better grasp of how to start this problem. Thanks!

**Comment by BrushXue** [comment]
I don't understand where is the integration coming from. It's just a simple 2nd order derivative.

**Comment by kershj** [comment]
Ok I guess I have remembered that incorrectly. How should we deal with the Y(1-Y) term in the equation? I am just looking for some guidance on how to start. Thanks

**Comment by BrushXue** [comment]
Just use the real y coordinate to calculate Y(1-Y).
You are solving T-equation. In this case Y is constant and nothing is special.
