### ISSUE TITLE
Mixed IVP and BVP Boundary Conditions with Shooting Method

### ISSUE THREAD

**Issue by bji219** [BrushXue/ME423-HelpDesk#18]
Hi Guanyang,

I have a question regarding the boundary conditions for the Assignment 6 Blasius equation: 

![image](https://user-images.githubusercontent.com/79180847/116310244-bbe18d00-a777-11eb-93ed-fb6a038623b6.png)

Given these boundary conditions, wouldn't there need to be a value for _f_ at infinity in order to solve using the shooting method? Since we are given a value for  _f_  and _f'_ but not for _f''_  at 0 it is not quite an IVP, but without _f_ at infinity it is not quite a BVP either. Is there a way to determine the value of _f_ at infinity which is not obvious in the notes 13c slide 6? Thank you!

**Comment by BrushXue** [comment]
When it says infinity, it is not a real infinity.
If you recall the 99% boundary layer thickness from ME430, <img src="https://render.githubusercontent.com/render/math?math=\eta=5.0"> is considered as the infinity here. The problem can be approximated as a BVP in [0,5].
However I don't recommend using 5.0 when heat equation is coupled. You can try a larger value, for example, solving the BVP in [0,10], and see if the result is different from [0,5].

**Comment by bji219** [comment]
Makes sense, thank you!

**Comment by BrushXue** [comment]
IVP method: Use [ode15s](https://www.mathworks.com/help/matlab/ref/ode15s.html) (ode45 will crash when the equation is stiff). Then construct a residual function <img src="https://render.githubusercontent.com/render/math?math=r=g(f''(0), \theta'(0))\geq 0">. The residual is 0 if and only if <img src="https://render.githubusercontent.com/render/math?math=f'(\eta_\infty)=1, \theta(\eta_\infty)=1">. Then use [fminsearch](https://www.mathworks.com/help/matlab/ref/fminsearch.html) to minimize the residual.

BVP method: Use [bvp4c](https://www.mathworks.com/help/matlab/ref/bvp4c.html) to solve 5 equations with 5 boundary conditions.

**Comment by LeoNardoW2R** [comment]
May I ask what are the 5 equations we need to solve?

**Comment by BrushXue** [comment]
> May I ask what are the 5 equations we need to solve?

Momentem equation:
3rd order ODE -> 3 * 1st order ODE
Energy equation:
2rd order ODE -> 2 * 1st order ODE
In total: 5 * 1st order ODE
