### ISSUE TITLE
Solving for Temperature using Energy Equation: Approach?

### ISSUE THREAD

**Issue by cmitch27** [BrushXue/ME423-HelpDesk#19]
I used the bvp4c method to solve for f. I'm trying to solve for Theta, but I'm having trouble figuring out which method is best. I've tried a finite difference approach, shooting method, and bvp4c for the energy equation. Could you steer me in the right direction or offer some advice as to which method to pursue?

**Comment by BrushXue** [comment]
Solving all variables at the same time might be easier. See https://github.com/BrushXue/ME423-HelpDesk/issues/18#issuecomment-829535042
