### ISSUE TITLE
Curve fits for theta prime vs prandtl number

### ISSUE THREAD

**Issue by kpw320** [BrushXue/ME423-HelpDesk#20]
In the notes we see that for m = 0 a Pr^(1/3) curve fit is used, as we might expect if we use the Reynolds-Colburn analogy. But in the notes for m = 1, we see a Pr^(2/5) curve fit. Should we use the Reynolds-Colburn analogy in all our cases? Or should we just find a good curve fit? Should we stick with integers in the power of the fit?

**Comment by BrushXue** [comment]
You are supposed to find out the parameter yourself.
Try to fit <img src="https://render.githubusercontent.com/render/math?math=\theta'(0)=a\mathrm{Pr}^{b} "> from the dataset <img src="https://render.githubusercontent.com/render/math?math=\mathrm{Pr}=\{0.1,0.3,\cdots,7.0,10.0\}">.
