### ISSUE TITLE
Problem When Solving ODE In MATLAB 

### ISSUE THREAD

**Issue by JackyPoka** [BrushXue/ME423-HelpDesk#21]
I'm using bvp4c to solve the ODE equation and I set η=5, then the warning appeared "Unable to meet the tolerance without using more than 2000 mesh points." But when I decrease the value η to 2, there was no warning coming out. Could I know how to solve this problem in MATLAB?  Thank you!
```

**Comment by BrushXue** [comment]
That’s why I recommend shooting method. bvp4c looks easy but you need to
carefully tune the initial condition otherwise it’ll easily diverge.

**Comment by JackyPoka** [comment]
Okay, Thank you
