### ISSUE TITLE
How to plot a nonlinear equation in Matlab

### ISSUE THREAD

**Issue by JackyPoka** [BrushXue/ME423-HelpDesk#3]
I got the value of θin, θ1, θs, and q by using fsolve in Matlab. However, I just can't figure out how to plot those equation in Matlab. My equation relate to θi is 10*(θi-θ1)+0.2*(θi^4-θ1^4)=.....
Could I know how to plot it? Thank you

**Comment by BrushXue** [comment]
Every time you get the root from `fsolve`, save it somewhere. For example,
```MATLAB
thetai=start:step:end;
b=[]; % Initialize empty matrix
for a=thetai
    x0=your_initial_value;
    root=fsolve(your_equation,x0);
    b=[b,root]; % Append the root column to the end of x
end
```
After the for loop you'll get a matrix b, each column is a root for a theta_i. On the other hand, each row is a value versus theta_i. Then you can extract each row and [plot](https://www.mathworks.com/help/matlab/ref/plot.html) it.

**Comment by JackyPoka** [comment]
> Every time you get the root from `fsolve`, save it somewhere. For example,
> 
> ```matlab
> thetai=start:step:end;
> b=[]; % Initialize empty matrix
> for a=thetai
>     x0=your_initial_value;
>     root=fsolve(your_equation,x0);
>     b=[b,root]; % Append the root column to the end of x
> end
> ```
> 
> After the for loop you'll get a matrix **b**, each column is the root for a certain **thetai**. On the other hand, each row is a variable versus theta_i. Then you can extract the row and [plot](https://www.mathworks.com/help/matlab/ref/plot.html) it.

Thank you!
