### ISSUE TITLE
How to define the position for I1 , I2 and N in the coefficient matrix and what should include in assignment 2?

### ISSUE THREAD

**Issue by JackyPoka** [BrushXue/ME423-HelpDesk#4]
I'm trying to create a coefficient matrix to solve the finite difference equation:
![image](https://user-images.githubusercontent.com/79382740/109428071-46e61700-79c3-11eb-9d1d-f1c1fa52d391.png)
I got these code as my coefficient, for 2<=i<=(I1-1)
```MATLAB
disp("A=[];
R2=1.5;
for i=1:0.1:R2
    a=-2*(1+(i-1)*0.1)-((1.25/9)^0.5)*((4*pi*0.1*2.5)/30)*i;
    A=[A,a];
end

B=[];
R2=1.5;
for i=1:0.1:R2
    b=(0.1)/(2*0.1)+1+(i-1)*0.1/(0.1)^2;
    B=[B,b];
end

C=[];
R2=1.5;
for i=1:0.1:R2
    c=(0.1)/(2*0.1)-1+(i-1)*0.1/(0.1)^2;
    C=[C,c];
end

Sa=sparse([1,2,3,4,5,6],[1,2,3,4,5,6],A,19,19);
Sb=sparse([2,3,4,5,6,7],[1,2,3,4,5,6],B,19,19);
Sc=sparse([1,2,3,4,5,6],[2,3,4,5,6,7],C,19,19);")
```
and I got the equation between I1 , I2 and N. The coefficient at I1,I2 is [9,2,-8,1,4] and at N is [-3,4,-1], but as I trying to create the coefficient between I1 (I2) and N, I couldn't figure out their position in the coefficient matrix . How could I define it ? and what should include in assignment 2? Thank you for your help.

**Comment by BrushXue** [comment]
1. Don't use hard-coding(write numbers explicitly in your equation). You'll have trouble debugging.
2. If you want to assign values to a sparse matrix, just do it like what you did in a dense matrix.
If you have the following equation that on point **i**
<img src="https://render.githubusercontent.com/render/math?math=ax_{i-1}%2Bbx_i%2Bcx_{i%2B1} = d">
simply assign

```MATLAB
A(i,i-1)=a;
A(i,i)=b;
A(i,i+1)=c;
B(i)=d;
```
3. See https://github.com/BrushXue/ME423-HelpDesk/issues/5

**Comment by JackyPoka** [comment]
Thank you! I got my coefficient matrix. However, as I was doing x=A/b. I got NaN, and Matlab indicates that my matrix is singular. Could I know how to fix it? Thank you!

**Comment by BrushXue** [comment]
Use [`spy()`](https://www.mathworks.com/help/matlab/ref/spy.html) to visualize you matrix. It will be easy to find out which part is going wrong.

**Comment by JackyPoka** [comment]
Thank you I think I found the problem.
