### ISSUE TITLE
Issue regarding Aij matrix

### ISSUE THREAD

**Issue by kershj** [BrushXue/ME423-HelpDesk#6]
To solve numerically using finite differencing, I am planning on using the x = A^-1 *b approach explained in the notes. I am curious whether a. this is a valid approach for this specific problem, and b., whether I have set up my code to generate the Aij matrix correctly.

This is what I have to create Aij:
```MATLAB
for j=1:N-1;
    for k=1:N-1;
        if j==k;
            A(j,k)=***;
        elseif j<k;
            A(j,k)=***;
        elseif j>k;
            A(j,k)=***;    
        end;
    end;
end;
```
Thanks for any help!
John

**Comment by kershj** [comment]
Sorry the formatting is not good, I was not sure how to embed from MATLAB.

**Comment by BrushXue** [comment]
1. Do NOT use `x=inv(A)*b. See https://www.mathworks.com/help/matlab/ref/inv.html
> Using A\b instead of inv(A)*b is two to three times faster, and produces residuals on the order of machine accuracy relative to the magnitude of the data.
2. I can only help you with the code structure. The syntax is definitely wrong. It should be something like:
```MATLAB
for j=1:N-1
    A(j,k)=something;
    A(j,k-1)=something;
    A(j,k+1)=something;    
end;
```
Your matrix structure should be similar to mine. See this [image](https://user-images.githubusercontent.com/12702149/109365270-c7d7ce00-785e-11eb-8a3b-0eea5ae73d61.png)

**Comment by kershj** [comment]
Thank you. One other question I have is what is ai'? Is it the derivative of ai with respect to i or R?

**Comment by BrushXue** [comment]
This question is really unnecessary. Radius is always R, but the index i is virtual.
