### ISSUE TITLE
Should the temperatures and heat fluxes we plot be normalized or unit

### ISSUE THREAD

**Issue by kpw320** [BrushXue/ME423-HelpDesk#7]
Should I be graphing temperature in Celsius, or the normalized temperature? Same question for heat flux.

**Comment by kpw320** [comment]
Also, should we plot against normalized distance, or distance in cm?

**Comment by BrushXue** [comment]
Temperature in °C and heat flux in W/m^2

The unit doesn't matter, as long as it metric.
