### ISSUE TITLE
Switching MATLAB

### ISSUE THREAD

**Issue by bji219** [BrushXue/ME423-HelpDesk#8]
Hi Guanyang- 
I have a question regarding the following MATLAB code- I am getting an error when running your example script for Assignment 3 (specifically the first switch line).
```MATLAB
Line:
switch boundary(i,j) % Return the type of the current node as we defined

Error:
SWITCH expression must be a scalar or a character vector.
```
It seems that the built in function "boundary" is returning an empty array for i & j = 1. Is there a way around this/is there an alternate way to build the matrix? Thanks!

**Comment by BrushXue** [comment]
It's just a variable name. You can change it to any name you want.

**Comment by bji219** [comment]
Got it, I did not see your update to "your_mesh_matrix". Since "boundary" is also a MATLAB built-in function, that was causing confusion. Thanks!
