### ISSUE TITLE
Definition of dimensionless heat transfer coefficient

### ISSUE THREAD

**Issue by kpw320** [BrushXue/ME423-HelpDesk#9]
In the problem statement we see M/k is used in setting up the boundary conditions, which is fine if M is measured in units that already include a length scale. However, in the actual given information we are given capital H for heat transfer coefficient, and what exactly this means for the problem depends on which length scale it's normalized too right? So my question is what is H in this problem. Is it aM/k, or possible bM/k. Or is it simply M/k if M is measured in units of k/b and then the coordinates are normalized.

**Comment by BrushXue** [comment]
`H` equals to `M/k` after normalization. So in assignment you don't have to normalize `H` again.
